Vagrant.configure("2") do |config|
  config.vm.define :vm1 do |vm1|
    vm1.vm.box = "trusty"
    vm1.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    vm1.vm.network "private_network", ip: "192.168.1.1"
    vm1.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true, id: "ssh"
    vm1.vm.network :forwarded_port, guest: 22, host: 2230
    vm1.vm.hostname = "vm1.test"
    vm1.vm.provision :puppet do |puppet|
       puppet.manifest_file = "vm1.pp"
       puppet.module_path = "../modules"
       puppet.options = "--verbose"
    end
  end
end
