Vagrant.configure("2") do |config|
  config.vm.define :vm1 do |vm1|
    vm1.vm.box = "trusty"
    vm1.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    vm1.vm.network "private_network", ip: "192.168.1.10"
    vm1.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true, id: "ssh"
    vm1.vm.network :forwarded_port, guest: 22, host: 2230
    vm1.vm.network :forwarded_port, guest: 8080, host: 8080
    vm1.vm.network :forwarded_port, guest: 5050, host: 5050
    vm1.vm.hostname = "vm1.test"
    vm1.vm.provision :puppet do |puppet|
       puppet.manifest_file = "vm1.pp"
       puppet.module_path = "../modules"
       puppet.options = "--verbose"
    end
  end

  config.vm.define :vm2 do |vm2|
    vm2.vm.box = "trusty"
    vm2.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    vm2.vm.network "private_network", ip: "192.168.1.11"
    vm2.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true, id: "ssh"
    vm2.vm.network :forwarded_port, guest: 22, host: 2232
    vm2.vm.hostname = "vm2.test"
    vm2.vm.provision :puppet do |puppet|
       puppet.manifest_file = "vm2.pp"
       puppet.module_path = "../modules"
       puppet.options = "--verbose"
    end
  end

  config.vm.define :vm3 do |vm3|
    vm3.vm.box = "trusty"
    vm3.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    vm3.vm.network "private_network", ip: "192.168.1.12"
    vm3.vm.network :forwarded_port, guest: 22, host: 2222, disabled: true, id: "ssh"
    vm3.vm.network :forwarded_port, guest: 22, host: 2233
    vm3.vm.hostname = "vm3.test"
    vm3.vm.provision :puppet do |puppet|
       puppet.manifest_file = "vm3.pp"
       puppet.module_path = "../modules"
       puppet.options = "--verbose"
    end
  end


end
